use pokemon_trader;
DROP TABLE IF EXISTS Friends;
DROP TABLE IF EXISTS SalesPosts;
DROP TABLE IF EXISTS UserPosts;
DROP TABLE IF EXISTS ItemSales;
DROP TABLE IF EXISTS PokemonSales;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS PokemonTeam;
DROP TABLE IF EXISTS Pokemon;
DROP TABLE IF EXISTS ItemTemplate;
DROP TABLE IF EXISTS PokemonTemplate;
DROP TABLE IF EXISTS Users;

